#!/usr/bin/env python3
"""Patch a Homebrew formula generated by poet with correct metadata.

Usage:
    python scripts/patch_formula.py Formula/oak-ci.rb \
        --version 1.0.5 \
        --url "https://files.pythonhosted.org/packages/.../oak_ci-1.0.5.tar.gz" \
        --sha256 "abc123..."

This script updates the formula to use the pip-in-venv install strategy
(pre-built wheels) instead of resource stanzas, avoiding build failures
for native dependencies like onnxruntime and flatbuffers.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

FORMULA_TEMPLATE = textwrap.dedent("""\
    class OakCi < Formula
      include Language::Python::Virtualenv

      desc "Codebase intelligence toolkit for development workflows"
      homepage "https://github.com/goondocks-co/open-agent-kit"
      url "{url}"
      sha256 "{sha256}"
      license "MIT"

      depends_on "python@3.13"

      def install
        # Create a full virtualenv (with pip) and install oak-ci with all deps.
        # We use python -m venv directly (not virtualenv_create) because Homebrew's
        # helper passes --without-pip. We need pip to install oak-ci with pre-built
        # wheels, since native deps like onnxruntime and flatbuffers lack sdists.
        python3 = "python3.13"
        system python3, "-m", "venv", libexec
        system libexec/"bin/pip", "install", "--upgrade", "pip"
        system libexec/"bin/pip", "install", "oak-ci==#{{version}}"
        bin.install_symlink libexec/"bin/oak"
      end

      test do
        assert_match version.to_s, shell_output("#{{bin}}/oak version")
        assert_match "Usage", shell_output("#{{bin}}/oak --help")
      end
    end
""")


def get_pypi_info(version: str) -> tuple[str, str]:
    """Fetch the sdist URL and sha256 from PyPI for the given version."""
    import json
    import urllib.request

    api_url = f"https://pypi.org/pypi/oak-ci/{version}/json"
    with urllib.request.urlopen(api_url) as resp:
        data = json.loads(resp.read())

    for entry in data["urls"]:
        if entry["packagetype"] == "sdist":
            return entry["url"], entry["digests"]["sha256"]

    raise RuntimeError(f"No sdist found for oak-ci {version}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate oak-ci Homebrew formula")
    parser.add_argument("output", type=Path, help="Path to write the formula")
    parser.add_argument("--version", required=True, help="Package version")
    parser.add_argument("--url", help="Override sdist URL (fetched from PyPI if omitted)")
    parser.add_argument("--sha256", help="Override sha256 (fetched from PyPI if omitted)")
    args = parser.parse_args()

    if args.url and args.sha256:
        url, sha256 = args.url, args.sha256
    else:
        print(f"Fetching PyPI metadata for oak-ci {args.version}...")
        url, sha256 = get_pypi_info(args.version)

    formula = FORMULA_TEMPLATE.format(url=url, sha256=sha256)
    args.output.write_text(formula)
    print(f"Wrote formula to {args.output}")


if __name__ == "__main__":
    main()
